### PR TITLE
feat: Add feature flag for ExploreV2

### PR DESCRIPTION
**Pull request by sandrade-dcl**
It adds the new feature flag `explorev2` that will be used by `unity-renderer` to enable/disable the new feature **[ExploreV2](https://www.notion.so/decentraland/PRD-Explore-V2-ab98e922c196488fb217596c888ce3d6)** (currently in development) and replace the old "**Explore & Play**" feature.

### CODE REVIEW

**Comment by menduz** [comment]
Hi Santi, I'd like to have this PR doing something like this instead:

```ts
type FeatureFlag = { enabled: boolean, variants: ... }

UnityInterface.PutFeatureFlags(flags: Dictionary<string, FeatureFlag>)
```

I don't consider adding individual feature flags is a scalable path, because this PR also touches the UI initialization logic and this may change the way some UI behave and it is very hard to test with different version combinations to ensure it won't break with rollouts.

The `PutFeatureFlags` instead, moves the control of the features back to unity and adds the flexibility to read any feature flag at any time and perform the changes in a more isolated/blackbox way, which is safer for both teams

**Comment by sandrade-dcl** [comment]
> Hi Santi, I'd like to have this PR doing something like this instead:
> 
> ```ts
> type FeatureFlag = { enabled: boolean, variants: ... }
> 
> UnityInterface.PutFeatureFlags(flags: Dictionary<string, FeatureFlag>)
> ```
> 
> I don't consider adding individual feature flags is a scalable path, because this PR also touches the UI initialization logic and this may change the way some UI behave and it is very hard to test with different version combinations to ensure it won't break with rollouts.
> 
> The `PutFeatureFlags` instead, moves the control of the features back to unity and adds the flexibility to read any feature flag at any time and perform the changes in a more isolated/blackbox way, which is safer for both teams

Hi @menduz! We the team have just talked about it today in the daily meeting and we are going to be working on this little refactor during the next week (the priorized issue is recorded [HERE](https://github.com/decentraland/unity-renderer/issues/1253)). So the plan will be left this PR temporally open and wait for the next week to finish the refactor. Is that okay with you?

**Review by Suduck — APPROVED** [review]

**Comment by menduz** [comment]
Yep, do you need a merge anyways?

**Comment by sandrade-dcl** [comment]
> Yep, do you need a merge anyways?

If you don't mind, I would prefer to merge, but if you don't like it I can keep this PR open in the meantime until the other refactor is done.

**Comment by menduz** [comment]
@sandrade-dcl merging, please do account for the revert in the issue related to feature flags. Thanks

**Review by menduz — APPROVED** [review]

**Pull request merged**
