### PR TITLE
feat: create one port per scene and migrate LoadScene message to protobuf

### PR DESCRIPTION
**Pull request by menduz**
Implements https://github.com/decentraland/protocol/pull/89
closes https://github.com/decentraland/sdk/issues/474

# What?

This PR separates the scenes from `renderer-protocol` rpc port. Creating one port per scene and implements the new Scene Controller RPC Service to message the renderer trough protobuf.

# What needs to be implemented from the renderer side?

Every time a port is created with a name matching `scene-\d+`, it should create a context enabled for scenes that supports the following methods

```protobuf
// The SceneController exists once per RPC port. Every scene is a independent
// port and thus, rpcContext and its lifecycle is controlled by the SceneController.
service RpcSceneControllerService {
  // creates a scene in the renderer
  rpc LoadScene(LoadSceneMessage) returns (LoadSceneResult){}
  // unloads the scene and releases its resources
  rpc UnloadScene(UnloadSceneMessage) returns (UnloadSceneResult){}
  // back and forth of CRDT messages
  rpc SendCrdt(CRDTSceneMessage) returns (CRDTSceneMessage) {}
  // back and forth of CRDT messages
  rpc GetCurrentState(GetCurrentStateMessage) returns (CRDTSceneMessage) {}
}
```

This new schema will apply both to SDK6 and SDK7 scenes.

The recommended implementation accepts *both* implementations in the renderer for a couple of releases. The kernel instead, will only use this approach.

------------------------------------
### TESTING
* Production testing link: https://play.decentraland.org/?kernel-branch=prepare-new-apis&renderer-branch=main

- SDK6 scenes work fine in preview mode
- [SDK6 scenes load/unload in prod](https://play.decentraland.org/?kernel-branch=prepare-new-apis&renderer-branch=main&position=100,100): move around and confirm scenes load/unload around the user
- [SDK7 scenes work fine in preview mode](https://playground.decentraland.org/?kernel-branch=prepare-new-apis&renderer-branch=main): after the explorer finishes loading on the right side, click on "RUN" and confirm that the loaded cube rotates fine
- [SDK7 scene load in prod at position=-129,-77](https://play.decentraland.org/?kernel-branch=prepare-new-apis&renderer-branch=main&position=-129%2C-77)
- [SDK7 scene messages in prod at position=-129,-77](https://play.decentraland.org/?kernel-branch=prepare-new-apis&renderer-branch=main&position=-129%2C-77): scene platforms should move
- [FULL "Release Candidate Test"](https://play.decentraland.org/?kernel-branch=prepare-new-apis&renderer-branch=main)

### CODE REVIEW

**Comment by pravusjif** [comment]
this PR should only be merged after [the renderer counterpart](https://github.com/decentraland/unity-renderer/pull/3700) is already in production.

**Comment by pravusjif** [comment]
Before merging this PR let's have someone from QA test with a regular Release Candidate Test just in case.

**Comment by menduz** [comment]
I'm seeing a lot of `Not implemented message: DestroyPort`, is that correct @pravusjif ?

**Comment by pbosio** [comment]
> I'm seeing a lot of `Not implemented message: DestroyPort`, is that expected @pravusjif ?

This was due to and old version of the RPC on the renderer side, we shouldn't be seeing those errors any more

**Comment by pravusjif** [comment]
- Renderer counterpart has been in production for a week now.
- We are currently awaiting test run from Keywords Testers before merging.

**Review by pravusjif — APPROVED** [review]

**Comment by pravusjif** [comment]
Keyword QA Finished running the test steps without problems.

**Pull request merged**
